#!/usr/bin/env python3
"""Generate the AY-P0 register-stream corpus into tools/ay_ref/streams/.

Mirrors tools/sid_ref/make_streams.py's rationale exactly (module_chip.md, applied
to the second chip in this module): each stream isolates one primitive or
interaction, so a scorecard row points at a specific piece of DSP. Output is
generated, not hand-written, for the same reason -- tone period values are a
function of the clock, and a hand-typed table is a silent tuning bug waiting
to happen. Committed so both sides of the comparison read the same corpus.

    python3 tools/ay_ref/make_ay_streams.py
"""

import os

CLOCK_ZX = 1773400.0
FRAME_RATE = 50.0
FRAME_CYCLES = int(round(CLOCK_ZX / FRAME_RATE))

# R7 mixer bits: tone-disable A/B/C then noise-disable A/B/C (1 = disabled).
T_A, T_B, T_C, N_A, N_B, N_C = (1 << i for i in range(6))


def tone_period(hz):
    """AY 12-bit tone period for a pitch: freq = clock/16/period."""
    return min(0xfff, max(1, int(round(CLOCK_ZX / 16.0 / hz))))


def note(semitones_from_a4):
    return 440.0 * (2.0 ** (semitones_from_a4 / 12.0))


def write_stream(name, lines, frames, model="ay"):
    os.makedirs("tools/ay_ref/streams", exist_ok=True)
    path = f"tools/ay_ref/streams/{name}.ayreg"
    with open(path, "w") as f:
        f.write(f"# generated by tools/ay_ref/make_ay_streams.py -- do not edit by hand\n")
        f.write(f"model {model}\nclock zx\nframes {frames}\n\n")
        f.write("\n".join(lines) + "\n")
    print(f"wrote {path}  ({frames} frames, {frames / FRAME_RATE:.2f} s)")


def w(frame, reg, val):
    return f"@{frame} {reg:02x} {val:02x}"


def tone_scale():
    """One channel, a one-octave chromatic scale -- isolates AyTone."""
    lines = [w(0, 0x07, 0xff & ~(T_A)), w(0, 0x08, 0x0f)]
    for i in range(13):
        p = tone_period(note(i))
        lines.append(w(i * 25, 0x00, p & 0xff))
        lines.append(w(i * 25, 0x01, (p >> 8) & 0x0f))
    write_stream("tone_scale", lines, 13 * 25 + 25)


def noise_only():
    """Pure noise, sweeping the 5-bit period -- isolates AyNoise."""
    lines = [w(0, 0x07, 0xff & ~(N_A)), w(0, 0x08, 0x0f)]
    for i, period in enumerate([1, 4, 8, 16, 31]):
        lines.append(w(i * 25, 0x06, period))
    write_stream("noise_sweep", lines, 5 * 25 + 25)


def envelope_shapes():
    """One channel, envelope-driven, stepping through all 10 distinct
    shapes -- isolates AyEnvelope. Tone held at a mid pitch so the envelope's
    audible effect (the "buzzer bass", module_chip.md's own phrase) is what's under
    test, not silence."""
    lines = [w(0, 0x07, 0xff & ~(T_A)), w(0, 0x08, 0x10)]  # e_on=1, volume irrelevant
    p = tone_period(note(-24))   # low buzzer-bass register
    lines += [w(0, 0x00, p & 0xff), w(0, 0x01, (p >> 8) & 0x0f)]
    lines += [w(0, 0x0b, 0x00), w(0, 0x0c, 0x08)]   # envelope period ~2 Hz-ish
    shapes = [0, 4, 8, 10, 11, 12, 14]   # the raw codes covering all 10 distinct shapes
    for i, shape in enumerate(shapes):
        lines.append(w(i * 100, 0x0d, shape))
    write_stream("envelope_shapes", lines, len(shapes) * 100 + 100)


def mixer_combos():
    """One channel, cycling tone-only / noise-only / tone+noise / neither
    (the documented "constant output" quirk, ay_envelope.h's ay_mix note) --
    isolates the mixer's AND-of-disables logic."""
    p = tone_period(note(0))
    lines = [w(0, 0x00, p & 0xff), w(0, 0x01, (p >> 8) & 0x0f),
             w(0, 0x06, 8), w(0, 0x08, 0x0f)]
    combos = [0xff & ~(T_A), 0xff & ~(N_A), 0xff & ~(T_A) & ~(N_A), 0xff]
    for i, mix in enumerate(combos):
        lines.append(w(i * 50, 0x07, mix))
    write_stream("mixer_combos", lines, len(combos) * 50 + 50)


def ym_vs_ay():
    """Same tone+volume sweep rendered under both DAC tables -- isolates the
    one real, documented difference between the two chip models."""
    lines = [w(0, 0x07, 0xff & ~(T_A))]
    p = tone_period(note(0))
    lines += [w(0, 0x00, p & 0xff), w(0, 0x01, (p >> 8) & 0x0f)]
    for i in range(16):
        lines.append(w(i * 20, 0x08, i))
    write_stream("volume_sweep_ay", lines, 16 * 20 + 20, model="ay")
    write_stream("volume_sweep_ym", lines, 16 * 20 + 20, model="ym")


if __name__ == "__main__":
    tone_scale()
    noise_only()
    envelope_shapes()
    mixer_combos()
    ym_vs_ay()
