// GENERATED by tools/speechgen.py gen -- do not hand-edit.
// Host-only phoneme classification for tools/host_render/render_speech.cpp's
// per-class acoustic checks. Parallel to phonemes.h's PHONEME_TARGETS[] (same
// order, same PHONEME_COUNT) but never linked into the device build -- the
// class a phoneme belongs to isn't runtime data, it's a fact about the table
// this generator already knows and shouldn't make the harness re-derive.
#pragma once

#include <cstdint>

enum PhonemeClass : uint8_t {
    PCLASS_VOWEL,
    PCLASS_NASAL,
    PCLASS_FRICATIVE_VL,
    PCLASS_FRICATIVE_VD,
    PCLASS_STOP_CLOSURE,
    PCLASS_STOP_BURST,
    PCLASS_OTHER,
};

inline constexpr uint8_t PHONEME_CLASS[] = {
    PCLASS_VOWEL,  // I
    PCLASS_VOWEL,  // E
    PCLASS_VOWEL,  // A
    PCLASS_VOWEL,  // O
    PCLASS_VOWEL,  // U
    PCLASS_VOWEL,  // IH
    PCLASS_VOWEL,  // AE
    PCLASS_VOWEL,  // AH
    PCLASS_VOWEL,  // UH
    PCLASS_VOWEL,  // ER
    PCLASS_VOWEL,  // AX
    PCLASS_VOWEL,  // EY
    PCLASS_VOWEL,  // AW
    PCLASS_VOWEL,  // AY
    PCLASS_VOWEL,  // OY
    PCLASS_NASAL,  // M
    PCLASS_NASAL,  // N
    PCLASS_NASAL,  // NG
    PCLASS_FRICATIVE_VL,  // S
    PCLASS_FRICATIVE_VL,  // SH
    PCLASS_FRICATIVE_VL,  // F
    PCLASS_FRICATIVE_VD,  // Z
    PCLASS_FRICATIVE_VD,  // V
    PCLASS_FRICATIVE_VL,  // TH
    PCLASS_FRICATIVE_VD,  // DH
    PCLASS_FRICATIVE_VD,  // ZH
    PCLASS_FRICATIVE_VL,  // HH
    PCLASS_VOWEL,  // L
    PCLASS_VOWEL,  // R
    PCLASS_VOWEL,  // W
    PCLASS_VOWEL,  // Y
    PCLASS_STOP_CLOSURE,  // P_CL
    PCLASS_STOP_CLOSURE,  // B_CL
    PCLASS_STOP_CLOSURE,  // T_CL
    PCLASS_STOP_CLOSURE,  // D_CL
    PCLASS_STOP_CLOSURE,  // K_CL
    PCLASS_STOP_CLOSURE,  // G_CL
    PCLASS_STOP_BURST,  // P_BR
    PCLASS_STOP_BURST,  // B_BR
    PCLASS_STOP_BURST,  // T_BR
    PCLASS_STOP_BURST,  // D_BR
    PCLASS_STOP_BURST,  // K_BR
    PCLASS_STOP_BURST,  // G_BR
    PCLASS_STOP_CLOSURE,  // CH_CL
    PCLASS_STOP_BURST,  // CH_BR
    PCLASS_STOP_CLOSURE,  // JH_CL
    PCLASS_STOP_BURST,  // JH_BR
    PCLASS_OTHER,  // SIL
};
