// GENERATED by tools/speechgen.py gen-vowel-ref from speech_vowel_reference.csv
// -- do not hand-edit.
//
// Independent published vowel-space reference (#32's real acceptance target:
// catch coefficient/data-entry errors the ear forgives). Deliberately a
// separate file from speech_phonemes.csv's own F/B targets -- comparing a
// measured formant against the same number that was typed in to author it
// proves nothing. This exists to survive *future* edits to
// speech_phonemes.csv: if a vowel row drifts from the published literature
// without this file being updated too, the harness's comparison against it
// (not against speech_phonemes.csv) is what catches that.
#pragma once

struct VowelRef { const char *symbol; float F1, F2, F3; };

inline constexpr VowelRef VOWEL_REFERENCE[] = {
    { "I", 270.0f, 2290.0f, 3010.0f },
    { "E", 530.0f, 1840.0f, 2480.0f },
    { "A", 730.0f, 1090.0f, 2440.0f },
    { "O", 570.0f, 840.0f, 2410.0f },
    { "U", 300.0f, 870.0f, 2240.0f },
    { "IH", 390.0f, 1990.0f, 2550.0f },
    { "AE", 660.0f, 1720.0f, 2410.0f },
    { "AH", 640.0f, 1190.0f, 2390.0f },
    { "UH", 440.0f, 1020.0f, 2240.0f },
    { "ER", 490.0f, 1350.0f, 1690.0f },
};
