// GENERATED by tools/xm2t00t/blob_format.py:generate_cpp_header() — do not hand-edit.
// Mirrors blob_format.py, the format's source of truth. Regenerate with:
//   python3 tools/xm2t00t/xm2t00t.py gen-header src/engines/tracker/blob_format.h
#pragma once

#include <cstdint>

static constexpr uint32_t T00T_BLOB_MAGIC_LEN = 4;
static constexpr char T00T_BLOB_MAGIC[5] = "T00T";
static constexpr uint32_t T00T_BLOB_VERSION = 1;
static constexpr uint32_t T00T_MAX_SAMPLE_FRAMES = 262144;  // Q18.14 cap
static constexpr uint32_t T00T_NOTES_PER_TABLE = 96;
static constexpr uint32_t T00T_SAMPLE_MAP_SIZE = 96;

enum class Effect : uint8_t {
    NONE = 0,
    ARPEGGIO = 1,
    PORTA_UP = 2,
    PORTA_DOWN = 3,
    TONE_PORTA = 4,
    VIBRATO = 5,
    TONE_PORTA_VOLSLIDE = 6,
    VIBRATO_VOLSLIDE = 7,
    TREMOLO = 8,
    SET_PANNING = 9,
    SAMPLE_OFFSET = 10,
    VOLUME_SLIDE = 11,
    POSITION_JUMP = 12,
    SET_VOLUME = 13,
    PATTERN_BREAK = 14,
    SET_SPEED = 15,
    SET_BPM = 16,
    SET_GLOBAL_VOLUME = 17,
    GLOBAL_VOLUME_SLIDE = 18,
    KEY_OFF = 19,
    SET_ENVELOPE_POSITION = 20,
    PANNING_SLIDE = 21,
    RETRIG_NOTE = 22,
    TREMOR = 23,
    EXTRA_FINE_PORTA_UP = 24,
    EXTRA_FINE_PORTA_DOWN = 25,
    FINE_PORTA_UP = 26,
    FINE_PORTA_DOWN = 27,
    SET_GLISSANDO_CONTROL = 28,
    SET_VIBRATO_CONTROL = 29,
    SET_FINETUNE = 30,
    PATTERN_LOOP = 31,
    SET_TREMOLO_CONTROL = 32,
    FINE_VOLSLIDE_UP = 33,
    FINE_VOLSLIDE_DOWN = 34,
    NOTE_CUT = 35,
    NOTE_DELAY = 36,
    PATTERN_DELAY = 37,
    UNKNOWN = 255,
};

enum class VolEffect : uint8_t {
    NONE = 0,
    SET_VOLUME = 1,
    VOLSLIDE_DOWN = 2,
    VOLSLIDE_UP = 3,
    FINE_VOLSLIDE_DOWN = 4,
    FINE_VOLSLIDE_UP = 5,
    SET_VIBRATO_SPEED = 6,
    VIBRATO = 7,
    SET_PANNING = 8,
    PANSLIDE_LEFT = 9,
    PANSLIDE_RIGHT = 10,
    TONE_PORTA = 11,
};

// Fixed at blob offset 0.
struct SongHeader {
    char magic[4];  // "T00T"
    uint32_t version;  // format version, currently 1
    uint32_t num_channels;
    uint32_t freq_table;  // 0 = Amiga (period table), 1 = Linear
    uint32_t num_orders;
    uint32_t num_patterns;
    uint32_t num_instruments;
    uint32_t num_samples;
    uint32_t default_tempo;  // ticks per row
    uint32_t default_bpm;
    uint32_t restart_order;
    uint32_t order_table_offset;  // -> uint8_t[num_orders]
    uint32_t pattern_table_offset;  // -> PatternHeader[num_patterns]
    uint32_t instrument_table_offset;  // -> InstrumentHeader[num_instruments]
    uint32_t sample_table_offset;  // -> SampleHeader[num_samples]
    uint32_t sample_data_offset;  // -> start of concatenated PCM + guard bytes
    uint32_t sample_data_bytes;  // total PCM+guard bytes; the SRAM residency size
    uint32_t total_size;  // whole blob size, for a bounds-checked copy
    char name[32];
    char tracker_name[24];  // XM header's tracker-name field (#24 display)
};
static_assert(sizeof(SongHeader) == 128, "SongHeader size drifted from blob_format.py");

// PatternHeader
struct PatternHeader {
    uint32_t num_rows;
    uint32_t event_offset;  // -> Event[num_rows * num_channels]
};
static_assert(sizeof(PatternHeader) == 8, "PatternHeader size drifted from blob_format.py");

// 6 bytes, flat array of num_rows * num_channels, row-major.
struct Event {
    uint8_t note;  // 0 = none, 1..96 = C-0..B-7, 97 = key off
    uint8_t instrument;  // 0 = none, else 1-based instrument index
    uint8_t vol_effect;  // VolEffect enum
    uint8_t vol_param;
    uint8_t effect;  // Effect enum
    uint8_t effect_param;  // raw param byte (both nibbles, or low nibble for decomposed Exy/Xxy)
};
static_assert(sizeof(Event) == 6, "Event size drifted from blob_format.py");

// EnvelopePoint
struct EnvelopePoint {
    uint16_t tick;
    uint16_t value;  // 0..64
};
static_assert(sizeof(EnvelopePoint) == 4, "EnvelopePoint size drifted from blob_format.py");

// InstrumentHeader
struct InstrumentHeader {
    uint32_t sample_map_offset;  // -> uint8_t[96], note -> in-instrument sample index, 0xFF = none
    uint32_t num_samples;
    uint32_t sample_index_offset;  // -> uint32_t[num_samples], global sample indices
    uint32_t vol_env_offset;  // -> EnvelopePoint[vol_env_count], 0 if unused
    uint32_t vol_env_count;
    uint32_t vol_env_sustain;
    uint32_t vol_env_loop_start;
    uint32_t vol_env_loop_end;
    uint32_t vol_env_flags;  // bit0 enabled, bit1 sustain, bit2 loop
    uint32_t pan_env_offset;
    uint32_t pan_env_count;
    uint32_t pan_env_sustain;
    uint32_t pan_env_loop_start;
    uint32_t pan_env_loop_end;
    uint32_t pan_env_flags;
    uint32_t vibrato_type;
    uint32_t vibrato_sweep;
    uint32_t vibrato_depth;
    uint32_t vibrato_rate;
    uint32_t volume_fadeout;
    char name[24];
};
static_assert(sizeof(InstrumentHeader) == 104, "InstrumentHeader size drifted from blob_format.py");

// SampleHeader
struct SampleHeader {
    uint32_t length;  // frames, not counting the guard byte
    uint32_t loop_start;
    uint32_t loop_end;
    uint32_t loop_type;  // 0 = none, 1 = forward, 2 = ping-pong
    int32_t finetune;
    int32_t relative_note;
    uint32_t default_volume;  // 0..64
    int32_t default_panning;  // 0..255, XM convention
    uint32_t data_offset;  // -> int8_t[length + 1] (PCM + guard) in the sample data region
    uint32_t note_increments_offset;  // -> uint32_t[96] Q8.24 phase increments, one per note
    char name[24];
};
static_assert(sizeof(SampleHeader) == 64, "SampleHeader size drifted from blob_format.py");

