// GENERATED by tools/speechgen.py gen-phrases from speech_phrases.txt -- do not hand-edit.
#pragma once

#include "phonemes.h"
#include "sequencer.h"

static constexpr uint8_t PHRASE_HELLO_WORLD_PHONEMES[] = { PH_HH, PH_E, PH_L, PH_O, PH_SIL, PH_W, PH_ER, PH_L, PH_D_CL, PH_D_BR, PH_SIL };  // "hello world"
static constexpr uint8_t PHRASE_GOOD_MORNING_PHONEMES[] = { PH_G_CL, PH_G_BR, PH_UH, PH_D_CL, PH_D_BR, PH_SIL, PH_M, PH_O, PH_R, PH_N, PH_IH, PH_NG, PH_SIL };  // "good morning"
static constexpr uint8_t PHRASE_NOW_PLAYING_PHONEMES[] = { PH_N, PH_AW, PH_SIL, PH_P_CL, PH_P_BR, PH_L, PH_EY, PH_IH, PH_NG, PH_SIL };  // "now playing"
static constexpr uint8_t PHRASE_TRACK_SAVED_PHONEMES[] = { PH_T_CL, PH_T_BR, PH_R, PH_AE, PH_K_CL, PH_K_BR, PH_SIL, PH_S, PH_EY, PH_V, PH_D_CL, PH_D_BR, PH_SIL };  // "track saved"
static constexpr uint8_t PHRASE_VOICE_TEST_PHONEMES[] = { PH_V, PH_OY, PH_S, PH_SIL, PH_T_CL, PH_T_BR, PH_E, PH_S, PH_T_CL, PH_T_BR, PH_SIL };  // "voice test"
static constexpr uint8_t PHRASE_DRUM_MACHINE_PHONEMES[] = { PH_DH, PH_AX, PH_SIL, PH_D_CL, PH_D_BR, PH_R, PH_AH, PH_M, PH_SIL, PH_M, PH_AX, PH_SH, PH_I, PH_N, PH_SIL };  // "the drum machine"

enum SpeechPhraseId : uint8_t {
    PHRASE_HELLO_WORLD,
    PHRASE_GOOD_MORNING,
    PHRASE_NOW_PLAYING,
    PHRASE_TRACK_SAVED,
    PHRASE_VOICE_TEST,
    PHRASE_DRUM_MACHINE,
    SPEECH_PHRASE_COUNT
};

inline constexpr SpeechUtterance SPEECH_PHRASES[SPEECH_PHRASE_COUNT] = {
    { PHRASE_HELLO_WORLD_PHONEMES, 11, 10 },  // "hello world"
    { PHRASE_GOOD_MORNING_PHONEMES, 13, 12 },  // "good morning"
    { PHRASE_NOW_PLAYING_PHONEMES, 10, 9 },  // "now playing"
    { PHRASE_TRACK_SAVED_PHONEMES, 13, 12 },  // "track saved"
    { PHRASE_VOICE_TEST_PHONEMES, 11, 10 },  // "voice test"
    { PHRASE_DRUM_MACHINE_PHONEMES, 15, 14 },  // "the drum machine"
};

inline constexpr const char *SPEECH_PHRASE_TEXT[SPEECH_PHRASE_COUNT] = {
    "hello world",
    "good morning",
    "now playing",
    "track saved",
    "voice test",
    "the drum machine",
};
