// GENERATED by tools/samgen.py gen-phrases from sam_phrases.txt -- do not hand-edit.
// Allophone indices are plain integers (sam2allophones.py's SAM_ALLOPHONE_NAMES
// ordering), not SAM_ID_* names -- sam_allophones.h is optional and gitignored,
// so this header must not depend on it existing. Meaningful once a generated
// allophone table is present locally; wraps into sam.h's small fixture otherwise
// (safe, not intelligible -- see module_speech.md's SAM Tract section).
#pragma once

#include "sam.h"

static constexpr uint8_t SAM_PHRASE_HELLO_WORLD_ALLOPHONES[] = { 36, 7, 24, 52, 0, 25, 15, 24, 57, 0 };  // "hello world"
static constexpr int8_t SAM_PHRASE_HELLO_WORLD_PITCH[] = { 0, 0, 0, 3, 0, 0, 3, 0, -2, 0 };
static constexpr uint8_t SAM_PHRASE_GOOD_MORNING_ALLOPHONES[] = { 60, 12, 57, 0, 27, 11, 23, 28, 6, 29, 0 };  // "good morning"
static constexpr int8_t SAM_PHRASE_GOOD_MORNING_PITCH[] = { 0, 3, 0, 0, 0, 3, 0, 0, 0, -2, 0 };
static constexpr uint8_t SAM_PHRASE_NOW_PLAYING_ALLOPHONES[] = { 28, 51, 0, 66, 24, 48, 6, 29, 0 };  // "now playing"
static constexpr int8_t SAM_PHRASE_NOW_PLAYING_PITCH[] = { 0, 3, 0, 0, 0, 3, 0, -2, 0 };
static constexpr uint8_t SAM_PHRASE_TRACK_SAVED_ALLOPHONES[] = { 69, 23, 8, 72, 0, 32, 48, 40, 57, 0 };  // "track saved"
static constexpr int8_t SAM_PHRASE_TRACK_SAVED_PITCH[] = { 0, 0, 3, 0, 0, 0, 3, 0, -2, 0 };
static constexpr uint8_t SAM_PHRASE_VOICE_TEST_ALLOPHONES[] = { 40, 50, 32, 0, 69, 7, 32, 69, 0 };  // "voice test"
static constexpr int8_t SAM_PHRASE_VOICE_TEST_PITCH[] = { 0, 3, 0, 0, 0, 3, 0, -2, 0 };
static constexpr uint8_t SAM_PHRASE_DRUM_MACHINE_ALLOPHONES[] = { 41, 13, 0, 57, 23, 10, 27, 0, 27, 13, 33, 5, 28, 0 };  // "the drum machine"
static constexpr int8_t SAM_PHRASE_DRUM_MACHINE_PITCH[] = { 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 3, -2, 0 };

enum SamPhraseId : uint8_t {
    SAM_PHRASE_HELLO_WORLD,
    SAM_PHRASE_GOOD_MORNING,
    SAM_PHRASE_NOW_PLAYING,
    SAM_PHRASE_TRACK_SAVED,
    SAM_PHRASE_VOICE_TEST,
    SAM_PHRASE_DRUM_MACHINE,
    SAM_PHRASE_COUNT
};

inline constexpr SamUtterance SAM_PHRASES[SAM_PHRASE_COUNT] = {
    { SAM_PHRASE_HELLO_WORLD_ALLOPHONES, SAM_PHRASE_HELLO_WORLD_PITCH, 10, 9 },  // "hello world"
    { SAM_PHRASE_GOOD_MORNING_ALLOPHONES, SAM_PHRASE_GOOD_MORNING_PITCH, 11, 10 },  // "good morning"
    { SAM_PHRASE_NOW_PLAYING_ALLOPHONES, SAM_PHRASE_NOW_PLAYING_PITCH, 9, 8 },  // "now playing"
    { SAM_PHRASE_TRACK_SAVED_ALLOPHONES, SAM_PHRASE_TRACK_SAVED_PITCH, 10, 9 },  // "track saved"
    { SAM_PHRASE_VOICE_TEST_ALLOPHONES, SAM_PHRASE_VOICE_TEST_PITCH, 9, 8 },  // "voice test"
    { SAM_PHRASE_DRUM_MACHINE_ALLOPHONES, SAM_PHRASE_DRUM_MACHINE_PITCH, 14, 13 },  // "the drum machine"
};

inline constexpr const char *SAM_PHRASE_TEXT[SAM_PHRASE_COUNT] = {
    "hello world",
    "good morning",
    "now playing",
    "track saved",
    "voice test",
    "the drum machine",
};
