#!/usr/bin/env python3
"""Generate the F0 register-stream corpus into tools/sid_ref/streams/.

Each stream isolates one primitive or one interaction, so a scorecard row
points at a specific piece of DSP rather than at "the sound". That is the whole
argument of history_fm.md §3 applied to this module: when the composite output is
wrong, a composite test cannot tell you which curve is wrong.

The streams are generated rather than hand-written because the frequency
register values are a function of the PAL master clock, and a hand-typed table
of them is a silent tuning bug waiting to happen. The output is committed --
both sides of the comparison read it, and a corpus that regenerates differently
would move every baseline number.

    python3 tools/sid_ref/make_streams.py
"""

import os
import textwrap

CLOCK_PAL = 985248.0
FRAME_CYCLES_PAL = 19656       # 312 lines x 63 cycles
FRAME_RATE = CLOCK_PAL / FRAME_CYCLES_PAL   # 50.125 Hz

# Register offsets within a voice block ($D400 + voice*7 + n).
FREQ_LO, FREQ_HI, PW_LO, PW_HI, CONTROL, ATTACK_DECAY, SUSTAIN_RELEASE = range(7)
FC_LO, FC_HI, RES_FILT, MODE_VOL = 0x15, 0x16, 0x17, 0x18

# Control register bits.
GATE, SYNC, RING, TEST = 0x01, 0x02, 0x04, 0x08
TRI, SAW, PULSE, NOISE = 0x10, 0x20, 0x40, 0x80

# Filter mode bits in $D418.
LP, BP, HP, V3OFF = 0x10, 0x20, 0x40, 0x80


def freq_reg(hz):
    """SID frequency register for a pitch, at the PAL clock.

    Fout = Fn * Fclk / 2^24, so Fn = Fout * 2^24 / Fclk. The 16-bit
    quantisation this rounds to is kept, not smoothed: module_chip.md §3 lists it as a
    signal-path limitation, and it is where vibrato steppiness comes from.
    """
    return min(0xffff, max(0, int(round(hz * 16777216.0 / CLOCK_PAL))))


def note(semitones_from_a4):
    return 440.0 * (2.0 ** (semitones_from_a4 / 12.0))


# Pitches used below, named for readability.
C3, E3, G3, C4, E4, G4, A4 = (note(n) for n in (-21, -17, -14, -9, -5, -2, 0))


class Stream:
    def __init__(self, name, doc, frames, model="6581"):
        self.name = name
        self.doc = doc
        self.frames = frames
        self.model = model
        self.writes = []

    def w(self, frame, reg, value):
        self.writes.append((frame, reg & 0x1f, value & 0xff))

    def voice(self, frame, v, reg, value):
        self.w(frame, v * 7 + reg, value)

    def set_freq(self, frame, v, hz):
        f = freq_reg(hz)
        self.voice(frame, v, FREQ_LO, f & 0xff)
        self.voice(frame, v, FREQ_HI, f >> 8)

    def set_pw(self, frame, v, pw12):
        self.voice(frame, v, PW_LO, pw12 & 0xff)
        self.voice(frame, v, PW_HI, (pw12 >> 8) & 0x0f)

    def set_fc(self, frame, fc11):
        self.w(frame, FC_LO, fc11 & 0x07)
        self.w(frame, FC_HI, (fc11 >> 3) & 0xff)

    def render(self):
        out = [f"# {self.name}", "#"]
        out += ["# " + line if line else "#"
                for line in textwrap.dedent(self.doc).strip().splitlines()]
        out += ["#",
                "# Generated by tools/sid_ref/make_streams.py -- edit that, not this.",
                "",
                f"model {self.model}",
                "clock pal",
                f"frames {self.frames}",
                ""]
        for frame, reg, value in self.writes:
            out.append(f"@{frame} {reg:02x} {value:02x}")
        return "\n".join(out) + "\n"


def build():
    streams = []

    # -- envelope and oscillator, one at a time ------------------------------

    s = Stream("saw_c3", """
        One sawtooth note at C3, gated for 2 s and released.

        The simplest possible stream, and the one that has to pass before any
        other number means anything: it exercises the accumulator, the sawtooth
        derivation, EnvSID's attack/decay/sustain/release path and the output
        stage, with no filter, no sync and no ring in the way.
        """, frames=200)
    s.w(0, MODE_VOL, 0x0f)
    s.set_freq(0, 0, C3)
    s.voice(0, 0, ATTACK_DECAY, 0x28)      # A=2 (16 ms), D=8 (100 ms)
    s.voice(0, 0, SUSTAIN_RELEASE, 0xa9)   # S=10, R=9 (250 ms)
    s.voice(0, 0, CONTROL, SAW | GATE)
    s.voice(100, 0, CONTROL, SAW)          # gate off at 2 s
    streams.append(s)

    s = Stream("waveforms", """
        Every waveform selection in turn on one voice, 25 frames each.

        Includes the combined waveforms, which is the point: reSID uses tables
        sampled from real chips and module_chip.md §13.5 defers t00t to a bitwise AND
        until P6. This stream is where that deferral gets a number instead of
        an adjective.
        """, frames=25 * 8)
    s.w(0, MODE_VOL, 0x0f)
    s.set_freq(0, 0, C4)
    s.set_pw(0, 0, 0x800)
    s.voice(0, 0, ATTACK_DECAY, 0x00)
    s.voice(0, 0, SUSTAIN_RELEASE, 0xf0)   # full sustain, so only timbre varies
    for i, wave in enumerate([TRI, SAW, TRI | SAW, PULSE, PULSE | TRI,
                              PULSE | SAW, PULSE | SAW | TRI, NOISE]):
        s.voice(i * 25, 0, CONTROL, wave | GATE)
    streams.append(s)

    s = Stream("adsr", """
        Eight ADSR settings, each gated for 40 frames and released for 25.

        Spread across the rate table rather than clustered: rates 0-3 are
        milliseconds and rates 11-15 are seconds, and the exponential decay
        segments only show up on the slow ones.
        """, frames=8 * 65)
    s.w(0, MODE_VOL, 0x0f)
    s.set_freq(0, 0, C4)
    for i, (ad, sr) in enumerate([(0x00, 0xf0), (0x08, 0x80), (0x4a, 0x88),
                                  (0x00, 0x08), (0x2c, 0x4c), (0x88, 0xf8),
                                  (0x0b, 0x0b), (0x1f, 0x2f)]):
        f = i * 65
        s.voice(f, 0, ATTACK_DECAY, ad)
        s.voice(f, 0, SUSTAIN_RELEASE, sr)
        s.voice(f, 0, CONTROL, SAW | GATE)
        s.voice(f + 40, 0, CONTROL, SAW)
    streams.append(s)

    s = Stream("pulse_sweep", """
        A pulse wave with its width swept once per frame, 5% to 95% and back.

        The iconic SID phasing sound, and the reason module_chip.md §6's pulse table is
        a per-frame (delta, duration) list rather than an LFO. Also the most
        sensitive test of the pulse comparator's boundary condition: an
        off-by-one in `top12 >= pw` shows up here as a hard click at the turn.
        """, frames=200)
    s.w(0, MODE_VOL, 0x0f)
    s.set_freq(0, 0, C3)
    s.voice(0, 0, ATTACK_DECAY, 0x00)
    s.voice(0, 0, SUSTAIN_RELEASE, 0xf0)
    s.voice(0, 0, CONTROL, PULSE | GATE)
    for f in range(200):
        t = f / 100.0
        if t > 1.0:
            t = 2.0 - t
        s.set_pw(f, 0, int(0x0cc + t * (0xf33 - 0x0cc)))
    streams.append(s)

    # -- modulation ----------------------------------------------------------

    s = Stream("sync_lead", """
        Voice 2 hard-synced to voice 1, with voice 1's pitch swept per frame.

        The classic sync lead. module_chip.md §4.4 warns that the frame VM must be able
        to target the modulator's frequency, "omit this and sync instruments
        sound static in a way easily misdiagnosed as a synthesis bug" -- so the
        source sweeps here and the synced voice does not.

        Also the stream that catches module_chip.md §4.1's sync error: the doc says
        hard sync is accumulator overflow, the reference syncs on the MSB
        *rising*, and the two differ by half an accumulator cycle. Same rate,
        different phase, audibly different timbre.
        """, frames=200)
    s.w(0, MODE_VOL, 0x0f)
    s.set_freq(0, 1, C4)                    # voice 2: the synced voice, fixed
    s.voice(0, 1, ATTACK_DECAY, 0x00)
    s.voice(0, 1, SUSTAIN_RELEASE, 0xf0)
    s.voice(0, 1, CONTROL, SAW | SYNC | GATE)
    s.voice(0, 0, ATTACK_DECAY, 0x00)       # voice 1: the sync source, silent
    s.voice(0, 0, SUSTAIN_RELEASE, 0x00)
    s.voice(0, 0, CONTROL, SAW)
    for f in range(200):
        t = f / 199.0
        s.set_freq(f, 0, C3 * (2.0 ** (2.0 * t)))
    streams.append(s)

    s = Stream("ring", """
        Voice 2 ring-modulated by voice 1, source pitch stepped per frame.

        Ring substitutes the destination's accumulator MSB with MSB XOR NOT
        source-MSB, and only when triangle is selected without sawtooth. The
        second half of that rule is the one an implementation forgets, so the
        stream ends with a sawtooth + ring section where nothing should change.
        """, frames=200)
    s.w(0, MODE_VOL, 0x0f)
    s.set_freq(0, 1, C4)
    s.voice(0, 1, ATTACK_DECAY, 0x00)
    s.voice(0, 1, SUSTAIN_RELEASE, 0xf0)
    s.voice(0, 1, CONTROL, TRI | RING | GATE)
    s.voice(0, 0, CONTROL, TRI)
    for f in range(0, 150, 10):
        s.set_freq(f, 0, note(-21 + (f // 10) % 12))
    s.voice(150, 1, CONTROL, SAW | RING | GATE)   # ring must become a no-op
    streams.append(s)

    # -- filter --------------------------------------------------------------

    s = Stream("filter_sweep", """
        A sawtooth through the lowpass, cutoff swept over the full 11-bit range
        and back, resonance 0.

        The direct test of sid_tables.h's fitted cutoff curve. The sweep covers
        the whole register range deliberately: the fit's first version saturated
        above fc = 1360 and produced a table whose top third was flat, which a
        sweep limited to the musically-common lower half would not have shown.
        """, frames=300)
    s.w(0, MODE_VOL, LP | 0x0f)
    s.w(0, RES_FILT, 0x01)                  # voice 1 through the filter, res 0
    s.set_freq(0, 0, C3)
    s.voice(0, 0, ATTACK_DECAY, 0x00)
    s.voice(0, 0, SUSTAIN_RELEASE, 0xf0)
    s.voice(0, 0, CONTROL, SAW | GATE)
    for f in range(300):
        t = f / 150.0
        if t > 1.0:
            t = 2.0 - t
        s.set_fc(f, int(t * 2047))
    streams.append(s)

    s = Stream("filter_resonance", """
        Cutoff parked mid-range, resonance stepped 0-15, then the mode bits
        swept LP, BP, HP, LP+HP (the notch a SID makes by summing two).

        module_chip.md §5.1's first change is that FilterMode becomes a *mask* because
        the SID sums outputs simultaneously. The LP+HP section is what proves
        it: a selector implementation renders one of the two and scores as a
        gain error rather than as the wrong filter.
        """, frames=20 * 16 + 4 * 30)
    s.w(0, MODE_VOL, LP | 0x0f)
    s.w(0, RES_FILT, 0x01)
    s.set_fc(0, 900)
    s.set_freq(0, 0, C3)
    s.voice(0, 0, ATTACK_DECAY, 0x00)
    s.voice(0, 0, SUSTAIN_RELEASE, 0xf0)
    s.voice(0, 0, CONTROL, SAW | GATE)
    for r in range(16):
        s.w(r * 20, RES_FILT, (r << 4) | 0x01)
    base = 20 * 16
    for i, mode in enumerate([LP, BP, HP, LP | HP]):
        s.w(base + i * 30, MODE_VOL, mode | 0x0f)
    streams.append(s)

    s = Stream("chord_filtered", """
        A C major triad, all three voices routed into the shared filter, with
        the cutoff swept.

        module_chip.md §3's summing-node intermodulation, and §5.2's reason for binding
        a chord of one instrument to one bus: the three voices sum *before* the
        6581 nonlinearity, so this is the only stream in the corpus where
        sid_filter.h's saturation does anything audible. Against a linear
        filter it renders as a clean chord and scores well on every metric
        except the ones that matter.
        """, frames=250)
    s.w(0, MODE_VOL, LP | 0x0f)
    s.w(0, RES_FILT, 0x07)                  # all three voices filtered
    for v, hz in enumerate((C3, E3, G3)):
        s.set_freq(0, v, hz)
        s.voice(0, v, ATTACK_DECAY, 0x09)
        s.voice(0, v, SUSTAIN_RELEASE, 0xc9)
        s.voice(0, v, CONTROL, SAW | GATE)
    for f in range(250):
        t = f / 125.0
        if t > 1.0:
            t = 2.0 - t
        s.set_fc(f, int(200 + t * 1600))
    for v in range(3):
        s.voice(200, v, CONTROL, SAW)
    streams.append(s)

    # -- the frame clock itself ----------------------------------------------

    s = Stream("arpeggio", """
        A three-note arpeggio at one note per frame, plus a one-frame noise
        attack transient on each cycle.

        This is the stream that tests the frame clock rather than any
        primitive. module_chip.md §6 calls the 50 Hz steppiness "the whole character"
        and §6.2 makes the frame rate a module-global constant because "a
        1-frame noise click at 50 Hz and at 200 Hz are different sounds". If
        the two renderers disagree about frame length by even a fraction of a
        percent, the error here is cumulative and unmistakable.
        """, frames=300)
    s.w(0, MODE_VOL, 0x0f)
    s.voice(0, 0, ATTACK_DECAY, 0x00)
    s.voice(0, 0, SUSTAIN_RELEASE, 0xf8)
    for f in range(300):
        step = f % 3
        s.set_freq(f, 0, (C4, E4, G4)[step])
        if f % 24 == 0:
            s.voice(f, 0, CONTROL, NOISE | GATE)     # one-frame transient
        elif f % 24 == 1:
            s.voice(f, 0, CONTROL, PULSE | GATE)
            s.set_pw(f, 0, 0x400)
    streams.append(s)

    return streams


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out_dir = os.path.join(here, "streams")
    os.makedirs(out_dir, exist_ok=True)
    for s in build():
        path = os.path.join(out_dir, s.name + ".sidreg")
        with open(path, "w") as f:
            f.write(s.render())
        print(f"  {path}  ({s.frames} frames, {len(s.writes)} writes)")


if __name__ == "__main__":
    main()
