#!/usr/bin/env python3
"""xm2t00t — XM -> t00t tracker blob converter (issue #14).

    xm2t00t.py convert <in.xm> <out_prefix> [--budget-kb N]
        Parse in.xm, build the blob (blob_writer.py), and write
        <out_prefix>_blob.h — a linkable `static const uint8_t
        ..._blob_data[]` array, same convention as the existing
        samples/*.h Fairlight headers. Prints the song-structure dump too.

    xm2t00t.py dump <in.xm>
        Print the song-structure dump only; writes nothing.

    xm2t00t.py gen-header <out.h>
        (Re)generate the C++ mirror of blob_format.py's struct/enum layout
        (see blob_format.py:generate_cpp_header). Not wired into
        CMakeLists.txt yet — #14 is host-only.

See tracker.md for the design background and blob_format.py for the wire
format itself (the source of truth this tool packs against).
"""

from __future__ import annotations

import argparse
import os
import sys

import blob_format as bf
import blob_writer
import xm_parser as xp

_LOOP_NAMES = {0: "none", 1: "forward", 2: "ping-pong"}


def format_dump(song: xp.XmSong) -> str:
    lines = [
        f"Title: {song.name!r}",
        f"Tracker: {song.tracker_name!r} (version 0x{song.version:04x})",
        f"Channels: {song.num_channels}",
        f"Frequency table: {'linear' if song.linear_freq else 'Amiga'}",
        f"Tempo/BPM: {song.default_tempo}/{song.default_bpm}  Restart order: {song.restart_position}",
        f"Orders ({len(song.order_table)}): {song.order_table}",
        f"Patterns ({len(song.patterns)}):",
    ]
    for i, pat in enumerate(song.patterns):
        lines.append(f"  [{i:3}] {pat.num_rows} rows")

    lines.append(f"Instruments ({len(song.instruments)}):")
    total_samples = 0
    for i, inst in enumerate(song.instruments):
        lines.append(f"  [{i:3}] {inst.name!r}  {len(inst.samples)} sample(s)")
        for j, s in enumerate(inst.samples):
            total_samples += 1
            lines.append(
                f"        sample[{j}] {s.name!r} len={s.length} "
                f"loop={_LOOP_NAMES[s.loop_type]} [{s.loop_start}:{s.loop_end}] "
                f"vol={s.volume} pan={s.panning} finetune={s.finetune} relnote={s.relative_note}"
            )
    lines.append(f"Total samples: {total_samples}")
    return "\n".join(lines)


def _sanitize_ident(name: str) -> str:
    out = "".join(c if (c.isalnum() or c == "_") else "_" for c in name)
    if not out or out[0].isdigit():
        out = "_" + out
    return out


def render_blob_header(ident: str, blob: bytes) -> str:
    lines = [
        "// GENERATED by tools/xm2t00t/xm2t00t.py convert — do not hand-edit.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        f"static constexpr uint32_t {ident}_blob_size = {len(blob)};",
        f"alignas(4) static const uint8_t {ident}_blob_data[{ident}_blob_size] = {{",
    ]
    row = []
    for byte in blob:
        row.append(f"0x{byte:02x}")
        if len(row) == 16:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def cmd_dump(args: argparse.Namespace) -> None:
    song = xp.parse_xm_file(args.input)
    print(format_dump(song))


def cmd_convert(args: argparse.Namespace) -> None:
    song = xp.parse_xm_file(args.input)
    try:
        blob = blob_writer.build_blob(song, sram_budget_bytes=args.budget_kb * 1024)
    except blob_writer.ConversionError as exc:
        print(f"xm2t00t: {args.input}: {exc}", file=sys.stderr)
        sys.exit(1)

    if args.raw_blob:
        with open(args.raw_blob, "wb") as f:
            f.write(blob)
        print(f"Wrote {args.raw_blob} ({len(blob)} bytes, raw blob)")
    if not args.raw_blob_only:
        ident = _sanitize_ident(os.path.basename(args.output))
        header_path = args.output + "_blob.h"
        with open(header_path, "w") as f:
            f.write(render_blob_header(ident, blob))
        print(f"Wrote {header_path} ({len(blob)} bytes, array `{ident}_blob_data`)")

    print(format_dump(song))


def cmd_gen_header(args: argparse.Namespace) -> None:
    with open(args.output, "w") as f:
        f.write(bf.generate_cpp_header())
    print(f"Wrote {args.output}")


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(prog="xm2t00t")
    sub = parser.add_subparsers(dest="command", required=True)

    p_convert = sub.add_parser("convert", help="parse an .xm file and emit a linkable blob header")
    p_convert.add_argument("input")
    p_convert.add_argument("output", help="output path prefix; writes <output>_blob.h")
    p_convert.add_argument("--budget-kb", type=int, default=bf.DEFAULT_SRAM_BUDGET_BYTES // 1024,
                            help="SRAM sample-data budget in KB (default: %(default)s, per tracker.md)")
    p_convert.add_argument("--raw-blob", metavar="PATH", default=None,
                            help="also write the raw binary blob to PATH (#17: consumed at runtime "
                                 "by tools/host_render's reference-diff harness, which loads an "
                                 "arbitrary corpus module without recompiling)")
    p_convert.add_argument("--raw-blob-only", action="store_true",
                            help="skip the linkable _blob.h header, write only --raw-blob")
    p_convert.set_defaults(func=cmd_convert)

    p_dump = sub.add_parser("dump", help="print song structure only; writes nothing")
    p_dump.add_argument("input")
    p_dump.set_defaults(func=cmd_dump)

    p_header = sub.add_parser("gen-header", help="(re)generate the C++ blob format mirror header")
    p_header.add_argument("output")
    p_header.set_defaults(func=cmd_gen_header)

    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
